# path to executable
METRICS_ORTHOGONALITY_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/orthogonality.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_NRRD_FILE)\
	$(addprefix input/,$(USER_INPUT_ORIENTATION_FILES))\
	input/$(MASK_FILE)

override OUTPUTS := output/$(METRICS_ORTHOGONALITY_NRRD_FILE)

override USER_PARAMETERS :=

override USER_BINARIES := METRICS_ORTHOGONALITY_BIN
