# path to executable
METRICS_PAIRWISE_PREIMAGE_CONTINUITY_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/pairwise_preimage_continuity.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_DISCRETE_NRRD_FILE)

override OUTPUTS := output/$(METRICS_PAIRWISE_PREIMAGE_CONTINUITY_NRRD_FILE)

override USER_PARAMETERS := PIXEL_RESOLUTION

override USER_BINARIES := METRICS_PAIRWISE_PREIMAGE_CONTINUITY_BIN
