# path to executable
METRICS_PAIRWISE_PREIMAGE_CONTINUITY_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/pairwise_preimage_continuity.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_NRRD_FILE)

override OUTPUTS = $(addprefix output/,$(foreach r,$(METRICS_RESOLUTION),$(call METRICS_PAIRWISE_PREIMAGE_CONTINUITY_NRRD_FILE,$r)))

override USER_PARAMETERS := METRICS_RESOLUTION

override USER_BINARIES := METRICS_PAIRWISE_PREIMAGE_CONTINUITY_BIN
