# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(ANNOTATIONS_FILE)\
	input/$(FLATMAP_NRRD_FILE)

override OUTPUTS := output/$(FLATVIEW_ANNOTATIONS_FILE)

override USER_PARAMETERS := FLATVIEW_ANNOTATIONS_COLORMAP\
	PIXEL_RESOLUTION

override USER_BINARIES := FLATPLOT_BIN
