# path to executable
METRICS_PREIMAGE_CONNECTEDNESS_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/preimage_connectedness.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_DISCRETE_NRRD_FILE)

override OUTPUTS := output/$(METRICS_PREIMAGE_CONNECTEDNESS_NRRD_FILE)

override USER_PARAMETERS := PIXEL_RESOLUTION

override USER_BINARIES := METRICS_PREIMAGE_CONNECTEDNESS_BIN
