# paths to executables
METRICS_PREIMAGE_GEOMETRY_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/preimage_geometry.py
EXTRACT_NRRD_Z_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/utils/extract_nrrd_z.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_DISCRETE_NRRD_FILE)\
	$(addprefix input/,$(USER_INPUT_ORIENTATION_FILES))

override OUTPUTS := output/$(METRICS_PREIMAGE_RADIUS_NRRD_FILE)\
	output/$(METRICS_PREIMAGE_CONICITY_NRRD_FILE)

override INTERMEDIATE := output/$(METRICS_PREIMAGE_GEOMETRY_NRRD_FILE)

override USER_PARAMETERS := PIXEL_RESOLUTION

override USER_BINARIES := METRICS_PREIMAGE_GEOMETRY_BIN\
	EXTRACT_NRRD_Z_BIN
