# paths to executables
FLATPATH_BIN := $(SOURCE_CODE_ROOT)/flatpath/flatpath
GET_DIMENSIONS_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/utils/get_dimensions.py
NRRD_TO_BINGZ_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/utils/nrrd_to_bingz.py
SETVOXELS_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/utils/setvoxels.py

# DO NOT EDIT BELOW THIS LINE
override CONVERTED_INPUTS := $(addprefix output/,$(subst .nrrd,.bin.gz,$(USER_INPUT_FILES)))

override INPUTS := $(addprefix input/,$(USER_INPUT_FILES))

override OUTPUTS := output/$(STREAMLINE_DERIVED_THICKNESS_FILE)

override INTERMEDIATE := output/$(DIMENSIONS_FILE)\
	$(CONVERTED_INPUTS)

override CLEAN_EXTRA := $(addprefix output/,$(subst .nrrd,.nhdr,$(USER_INPUT_FILES)))

override USER_PARAMETERS := FLATPATH_BLOCKSIZE\
	FLATPATH_TIMESTEP\
	FLATPATH_MAXITER\
	FLATPATH_EPSILON_ZERO\
	FLATPATH_EPSILON_ONE\
	FLATPATH_NSTEP_PATH\
	FLATPATH_EXTRA

override USER_BINARIES := FLATPATH_BIN\
	GET_DIMENSIONS_BIN\
	NRRD_TO_BINGZ_BIN\
	SETVOXELS_BIN
