# paths to executables
EXTRACT_ISOSURFACE_VOXELS_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/utils/extract_iso_voxels.py
EXTRACT_DOTS_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/utils/extract_dots.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(RELATIVE_DEPTH_FILE)

override OUTPUTS := output/$(ISOSURFACE_NRRD_FILE)\
	output/$(ISOSURFACE_DOTS_FILE)

override USER_PARAMETERS := PROJECTION_SURFACE_DSTAR\
	PROJECTION_SURFACE_SIDE

override USER_BINARIES := EXTRACT_ISOSURFACE_VOXELS_BIN\
	EXTRACT_DOTS_BIN
