# path to executable
METRICS_PREIMAGE_SIZE_UNIFORMITY_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/preimage_size_uniformity.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_DISCRETE_NRRD_FILE)

override OUTPUTS = $(addprefix output/,$(foreach r,$(METRICS_RESOLUTION),$(call METRICS_PREIMAGE_SIZE_UNIFORMITY_NRRD_FILE,$r)))

override USER_PARAMETERS := METRICS_RESOLUTION

override USER_BINARIES := METRICS_PREIMAGE_SIZE_UNIFORMITY_BIN
