# path to executable
METRICS_PREIMAGE_SIZE_UNIFORMITY_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/preimage_size_uniformity.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_DISCRETE_NRRD_FILE)

override OUTPUTS := output/$(METRICS_PREIMAGE_SIZE_UNIFORMITY_NRRD_FILE)

override USER_PARAMETERS := PIXEL_RESOLUTION

override USER_BINARIES := METRICS_PREIMAGE_SIZE_UNIFORMITY_BIN
