# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(VOXEL_PROJECTIONS_FILE)

override OUTPUTS := output/$(VOXEL_PROJECTIONS_INDEX_FILE) \
	output/$(VOXEL_PROJECTIONS_POSITION_FILE)

override USER_PARAMETERS :=

override USER_BINARIES :=
