# path to executable
METRICS_USAGE_FRACTION_BIN := $(PYTHON3) $(SOURCE_CODE_ROOT)/metrics/usage_fraction.py

# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(FLATMAP_DISCRETE_NRRD_FILE)

override OUTPUTS := output/$(METRICS_USAGE_FRACTION_DISCRETE_FILE)

override USER_PARAMETERS := METRICS_RESOLUTION

override USER_BINARIES := METRICS_USAGE_FRACTION_BIN
