# DO NOT EDIT BELOW THIS LINE
override INPUTS := input/$(NEAREST_VERTICES_FILE)\
	input/$(FLAT_MESH_FILE)

override OUTPUTS := output/$(METRICS_USAGE_FRACTION_FILE)

override USER_PARAMETERS :=

override USER_BINARIES :=
