RANK 2
DIMENSION-SIZES _len 3
PATH streamlines/_num
INPUT-CLASS TEXTFP
INPUT-SIZE 32
OUTPUT-CLASS FP
OUTPUT-SIZE 32
OUTPUT-ARCHITECTURE IEEE
OUTPUT-BYTE-ORDER LE
CHUNKED-DIMENSION-SIZES 100 3
COMPRESSION-TYPE GZIP
