# DO NOT EDIT BELOW THIS LINE
FLATVIEW_DATA_NRRD_FILE = $(notdir $(FLATVIEW_DATA_INPUT_FILE))
FLATVIEW_DATA_PNG_FILE = $(subst .nrrd,.png,$(FLATVIEW_DATA_NRRD_FILE))

override INPUTS := input/$(FLATMAP_NRRD_FILE)\
	input/$(FLATVIEW_DATA_NRRD_FILE)

override OUTPUTS := output/$(FLATVIEW_DATA_PNG_FILE)

override USER_PARAMETERS := FLATPLOT_DATA_EXTRA

override USER_BINARIES := FLATPLOT_BIN
